name: "Check Codecov Config"
description: "Verify the validity of your codecov.yaml file"

runs:
  using: "composite"
  steps:
    - id: changes
      name: Check changed paths
      uses: dorny/paths-filter@v2
      with:
        filters: |
          codecov:
            - "codecov.yml"
    - name: Validate codecov.yml
      if: steps.changes.outputs.codecov == 'true'
      shell: bash
      # TODO: When GitHub Actions upgrades to curl 7.76+ replace the line below with
      #       curl --fail-with-body --data-binary @codecov.yml https://codecov.io/validate
      #       Until then, go up-vote https://stackoverflow.com/a/67216965/90297
      #       GitHub VM info: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md
      run: curl -s -o - -w "\n%{http_code}\n" --data-binary @codecov.yml https://codecov.io/validate | awk '{l[NR] = $0} END {for (i=1; i<=NR-1; i++) print l[i]}; END{ if ($0<200||$0>299) exit $0 }'
